### ISSUE TITLE
In the db.html template static file issue

### ISSUE THREAD

**Issue by abhijit77github** [heroku/python-getting-started#100]
In the db.html template in the hello app section {% load staticfiles  %} is not working  ,correct tag is
 {% load static %}, after this correction working well.

**Comment by alisherbek-rakhimov** [comment]
Please, fix it in db.html, if even it is a miserable bug, newbies can't figure it out on their own

**Comment by edmorley** [comment]
Fixed by #95 - sorry for the delay!
