### ISSUE TITLE
Django 1.8 TEMPLATE_DEBUG deprecation warning

### ISSUE THREAD

**Issue by aviaryan** [heroku/python-getting-started#15]
Same issue as https://github.com/heroku/heroku-django-template/issues/26

> I get the following warning with the template.
WARNINGS:
?: (1_8.W001) The standalone TEMPLATE_* settings were deprecated in Django 1.8 and the TEMPLATES dictionary takes precedence. You must put the values of the following settings into your default TEMPLATES dict: TEMPLATE_DEBUG.
It's nothing serious, and can be easily solved with this
https://stackoverflow.com/questions/32445953/django-app-works-fine-but-getting-a-template-warning-message

**Comment by kennethreitz** [comment]
Fixed!
