### ISSUE TITLE
Not clear how to reference HEROKU_POSTGRESQL_GREEN_URL and other color db variables.

### ISSUE THREAD

**Issue by DavidPratten** [heroku/python-getting-started#221]
While <https://github.com/heroku/python-getting-started/blob/main/gettingstarted/settings.py> says

```
`DATABASE_URL` will be set automatically by Heroku when a database addon is attached to your Heroku app.
```
in actual fact this wasn't true in my case.  The variable was called `HEROKU_POSTGRESQL_GREEN_URL`

I expect that future noobie users will be assisted if the example calls out the variability in the naming of the `DATABASE_URL` environment variable and shows how to discover what it is called and how to incorporate the actual name.

Something like this:

```
if IS_HEROKU_APP:
    # In production on Heroku the database configuration is derived from a `DATABASE_URL` 
    # environment variable by the dj-database-url package. `DATABASE_URL` or a similar color variable will be set
    # automatically by Heroku when a database addon is attached to your Heroku app. 
    # Run 'heroku config' to find the name of your `DATABASE_URL` and update the code below. See:
    # https://devcenter.heroku.com/articles/provisioning-heroku-postgres
    # https://github.com/jazzband/dj-database-url
    DATABASES = {
        "default": dj_database_url.config(
            env='DATABASE_URL',
            conn_max_age=600,
            conn_health_checks=True,
            ssl_require=True,
        ),
    }
```

**Comment by edmorley** [comment]
@DavidPratten Hi! Thank you for the feedback.

The default env var is always named `DATABASE_URL` for the first database added to the app. The additional colour name variants are only seen when multiple databases are added, per:
https://devcenter.heroku.com/articles/provisioning-heroku-postgres#application-config-vars

In your case, were you intentionally using multiple databases (and so wanting to understand how to adapt `dj_database_url` to that use-case, or were you following the tutorial and had accidentally added multiple DBs?

**Comment by DavidPratten** [comment]
Hi Ed,

When I created my instance, I created just a single database, and only
once, and Heroku added it as a color name. I agree that this is not what
the documentation says should happen.


All the best,


David Pratten

**Comment by edmorley** [comment]
Hi David

If you run `heroku addons`, do you see several DB addons now? 

Also, was your Heroku account created before May 15, 2023? Since older accounts have a legacy [auto-provisioning feature](https://devcenter.heroku.com/articles/python-support#database-auto-provisioning) enabled, though the tutorial content on Dev Center has been written in such a way that the auto-provisioning shouldn't occur for older accounts, so long as the tutorial is followed in sequence.

**Comment by DavidPratten** [comment]
Hi Ed,

No. Its a new account. When I created my instance, I created just a single database, and only once, and Heroku added it as a color name.

David

**Comment by edmorley** [comment]
Ok that's very strange - not sure what happened in your case. 

I've just merged #224 which hopefully improves the UX in this case.

**Comment by edmorley** [comment]
I also filed https://github.com/jazzband/dj-database-url/issues/248

**Comment by DavidPratten** [comment]
Awesome, thanks for the update!
