### ISSUE TITLE
Clone request link 

### ISSUE THREAD

**Issue by tkovalsky** [heroku/python-getting-started#42]
Hi, I had issues cloning the file when using the syntax provided.  I used `git clone https://github.com/heroku/python-getting-started.git` to download the repo

**Comment by aekpan1242** [comment]
aansreela

**Comment by aekpan1242** [comment]
aansreela

**Comment by CaseyFaist** [comment]
This is based on whether you're using SSH or HTTPS to clone the repo - to use SSH, there are other setup steps required - learn about this Github feature [here](https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/).

Totally agree that HTTPS is the better choice for the getting started app and would be more consistent with other Heroku documentation. Update can be tracked in PR #64 👍
