### ISSUE TITLE
Application Error + GDAL_LIBRARY_PATH

### ISSUE THREAD

**Issue by trexodore** [heroku/python-getting-started#66]
Whenever I follow the Heroku get started instructions for Python I end up making an app that ultimately results in a page with "Application Error". Through researching the logs I have 3 instances of this error `at=error code=H10 desc="App crashed" method=GET path="/robots.txt" host=desolate-eyrie-96916.herokuapp.com`. After trying this `heroku run python manage.py migrate` command I get this error `django.core.exceptions.ImproperlyConfigured: Could not find the GDAL library (tried "gdal", "GDAL", "gdal2.2.0", "gdal2.1.0", "gdal2.0.0", "gdal1.11.0", "gdal1.10.0", "gdal1.9.0"). Is GDAL installed? If it is, try setting GDAL_LIBRARY_PATH in your settings.`. I even had my colleague try on his computer and he was receiving the same errors.

**Comment by CaseyFaist** [comment]
Thanks for opening, and sorry for the confusion! Fix for this should be coming out later today 👍 you can track progress in #64

**Comment by CaseyFaist** [comment]
This should be fixed with #64
