### ISSUE TITLE
Default database engine is not Postgres

### ISSUE THREAD

**Issue by dariagrudzien** [heroku/python-getting-started#68]
In the repo the default database engine is set to Sqlite3, while the tutorial uses Postgres:
https://github.com/heroku/python-getting-started/blob/master/gettingstarted/settings.py#L80
https://devcenter.heroku.com/articles/getting-started-with-python#provision-a-database

It would be helpful if the repo showed how to work with `DATABASE_URL` variable instead of hardcoding the database credentials from the app datastore credentials, which also requires looking up an example - we used https://www.digitalocean.com/community/tutorials/how-to-use-postgresql-with-your-django-application-on-ubuntu-14-04 

That would be very helpful for beginners. Thanks!

**Comment by staeff** [comment]
Good catch! The Django Girls Tutorial also has a deployment chapter, which uses Heroku und describes how to set up Postgres: https://tutorial-extensions.djangogirls.org/en/heroku/
