### ISSUE TITLE
DEBUG=False for deployed application?

### ISSUE THREAD

**Issue by gghez** [heroku/python-getting-started#75]
Project, once deployed, is still in debug mode (django debug) which does not fit to django deployed application guideline (DEBUG=False).

Maybe some _settings.py_ adaptation is needed to load this DEBUG value from _os.environ_ ?

**Comment by marti1125** [comment]
debug in false did not work in heroku 😢

**Comment by edmorley** [comment]
As of #167, DEBUG is no longer enabled for apps deployed on Heroku.
