### ISSUE TITLE
Loading staticfiles module is deprecated in favor of static

### ISSUE THREAD

**Issue by gghez** [heroku/python-getting-started#76]
https://github.com/heroku/python-getting-started/blob/2fde3b47d3a63641e27cc4647712bd2911631f0e/hello/templates/index.html#L2

**Comment by antnieszka** [comment]
This will crash getting started site with Django 3.0 out :( It did for me.

**Comment by chandra10207** [comment]
I got the same issue. 

`

Request Method: | GET
-- | --
https://fdweb.herokuapp.com/
3.0
TemplateSyntaxError
'staticfiles' is not a registered tag library. Must be one of: admin_list admin_modify admin_urls cache i18n l10n log rest_framework static tz
/app/.heroku/python/lib/python3.7/site-packages/django/template/defaulttags.py in find_library, line 1025
/app/.heroku/python/bin/python
3.7.3
['/app/.heroku/python/bin',  '/app',  '/app/.heroku/python/lib/python37.zip',  '/app/.heroku/python/lib/python3.7',  '/app/.heroku/python/lib/python3.7/lib-dynload',  '/app/.heroku/python/lib/python3.7/site-packages']
Sun, 8 Dec 2019 08:09:11 +0000
`

**Comment by chandra10207** [comment]
I didn't see any solution on #78 
Can you please tell me how to fix this.

**Comment by AntonDeCarrion** [comment]
> I didn't see any solution on #78
> Can you please tell me how to fix this.

Line 2 of hello/templates/db.html should look like this
    {% load static %}
at least that's what worked for me. Good luck.

Thanks @gghez :1st_place_medal: for the tip, I was running into an existential sintax error

**Comment by antnieszka** [comment]
Same for hello/templates/index.html 😉 
https://github.com/heroku/python-getting-started/pull/78/files

**Comment by edmorley** [comment]
Fixed by #95 - sorry for the delay!
