### ISSUE TITLE
API app setup no longer works

### ISSUE THREAD

**Issue by silverbux** [heroku/python-getting-started#8]
```
curl -n -X POST https://api.heroku.com/app-setups \
-H "Content-Type:application/json" \
-H "Accept:application/vnd.heroku+json; version=3" \
-d '{"source_blob": { "url":"https://github.com/heroku/python-getting-started/tarball/master/"} }'
```
Please checkout PR https://github.com/heroku/python-getting-started/pull/7 for reference.

same issue on PHP which was solve by same solution https://github.com/heroku/php-getting-started/pull/8

**Comment by jonmountjoy** [comment]
Fixed via https://github.com/heroku/python-getting-started/pull/7 thanks
