### ISSUE TITLE
Python version is out of date

### ISSUE THREAD

**Issue by jkutner** [heroku/python-getting-started#96]
When deploying this app, the buildpack shows the message:

```
remote: -----> Python app detected
remote:  !     Python has released a security update! Please consider upgrading to python-3.7.6
remote:        Learn More: https://devcenter.heroku.com/articles/python-runtimes
```

**Comment by flexbox** [comment]
Hey @jkutner 

I think you can close this issue 
fixed with 
https://github.com/heroku/python-getting-started/commit/1f8fa8c0f2eb90d3cb97d09e489d27a34ae4c0a8

😉

**Comment by edmorley** [comment]
@flexbox Thank you :-)

(Longer term I would like to add support to the Python buildpack for requesting the latest path version using something like a wildcard or X.Y version specifier, which will make manual version bumps here unnecessary)
