### ISSUE TITLE
Fix require for "Provision a database" section of the tutorial

### ISSUE THREAD

**Issue by parvparkhiya** [heroku/python-getting-started#97]
`{% load staticfiles %}` needs to be replaced with `{% load static %}`  in `\hello\templates\db.html` to work in Django 3.0

It throws an error otherwise when accessing https://appname.herokuapp.com/db/

Tutorial: [https://devcenter.heroku.com/articles/getting-started-with-python#provision-a-database](https://devcenter.heroku.com/articles/getting-started-with-python#provision-a-database)

**Comment by edmorley** [comment]
Fixed by #95 - sorry for the delay!
